import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Privacy Policy', style: TextStyle(color: Colors.white)),
        backgroundColor: Colors.black,
        iconTheme: IconThemeData(color: Colors.white),
      ),
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Colors.purple.shade200,
              Colors.blue.shade200,
              Colors.pink.shade100,
            ],
          ),
        ),
        child: SingleChildScrollView(
          padding: EdgeInsets.all(20),
          child: Container(
            padding: EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.white.withOpacity(0.9),
              borderRadius: BorderRadius.circular(15),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildTitle('Privacy Policy'),
                _buildLastUpdated('April 23, 2025'),
                _buildSection(
                  'Introduction',
                  'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\nWe use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Free Privacy Policy Generator.',
                ),
                _buildSection(
                  'Interpretation',
                  'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
                ),
                _buildSubsection('Definitions', [
                  'Account means a unique account created for You to access our Service or parts of our Service.',
                  'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                  'Application refers to SportEve, the software program provided by the Company.',
                  'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to SportEve.',
                  'Country refers to: Rajasthan, India',
                  'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
                  'Personal Data is any information that relates to an identified or identifiable individual.',
                  'Service refers to the Application.',
                  'Service Provider means any natural or legal person who processes the data on behalf of the Company.',
                  'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
                  'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
                ]),
                _buildSection(
                  'Types of Data Collected',
                  'Personal Data:\nWhile using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include:\n• Email address\n• First name and last name\n• Phone number\n• Usage Data',
                ),
                _buildSection(
                  'Usage Data',
                  'Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device\'s Internet Protocol address, browser type, browser version, pages visited, time and date of visit, time spent on pages, unique device identifiers and other diagnostic data.\n\nWhen You access the Service by or through a mobile device, We may collect certain information automatically, including device type, unique ID, IP address, mobile operating system, browser type, and other diagnostic data.',
                ),
                _buildSection(
                  'Information Collection',
                  'While using Our Application, We may collect with Your prior permission:\n• Pictures and other information from your Device\'s camera and photo library\n\nYou can enable or disable access to this information at any time through Your Device settings.',
                ),
                _buildSection(
                  'Use of Personal Data',
                  'The Company may use Personal Data for:\n• Providing and maintaining our Service\n• Managing Your Account\n• Performance of contract\n• Contacting You\n• Providing news and offers\n• Managing requests\n• Business transfers\n• Other purposes such as data analysis and service improvement',
                ),
                _buildSection(
                  'Sharing of Personal Data',
                  'We may share Your information with:\n• Service Providers\n• Business partners\n• Affiliates\n• Other users when you interact in public areas\n• During business transfers\n• With Your consent',
                ),
                _buildSection(
                  'Data Retention',
                  'We retain Your Personal Data only as long as necessary for the purposes set out in this Privacy Policy or as required by law. Usage Data is generally retained for a shorter period.',
                ),
                _buildSection(
                  'Data Transfer',
                  'Your information may be transferred to computers located outside of Your state, province, country, or governmental jurisdiction. Your consent to this Privacy Policy followed by submission represents Your agreement to that transfer.',
                ),
                _buildSection(
                  'Delete Your Personal Data',
                  'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.',
                ),
                _buildSection(
                  'Disclosure of Personal Data',
                  'We may disclose Your Personal Data in good faith when necessary to:\n• Comply with legal obligations\n• Protect and defend Company rights\n• Prevent or investigate possible wrongdoing\n• Protect personal safety of users\n• Protect against legal liability',
                ),
                _buildSection(
                  'Security of Your Personal Data',
                  'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or electronic storage is 100% secure.',
                ),
                _buildSection(
                  'Children\'s Privacy',
                  'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.',
                ),
                _buildSection(
                  'Links to Other Websites',
                  'Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for third-party sites.',
                ),
                _buildSection(
                  'Changes to this Privacy Policy',
                  'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.',
                ),
                _buildSection(
                  'Contact Us',
                  'If you have any questions about this Privacy Policy, You can contact us:\nBy email: manishanwlaiitrpr@gmail.com',
                ),
                SizedBox(height: 20),
                Center(
                  child: TextButton(
                    onPressed: () => Navigator.pop(context),
                    child: Text('Close'),
                    style: TextButton.styleFrom(
                      backgroundColor: Colors.black,
                      foregroundColor: Colors.white,
                      padding: EdgeInsets.symmetric(
                        horizontal: 30,
                        vertical: 15,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildTitle(String text) {
    return Padding(
      padding: EdgeInsets.only(bottom: 20),
      child: Center(
        child: Text(
          text,
          style: TextStyle(
            fontSize: 24,
            fontWeight: FontWeight.bold,
            color: Colors.black,
          ),
        ),
      ),
    );
  }

  Widget _buildLastUpdated(String date) {
    return Padding(
      padding: EdgeInsets.only(bottom: 20),
      child: Text(
        'Last updated: $date',
        style: TextStyle(
          fontSize: 16,
          color: Colors.grey[600],
          fontStyle: FontStyle.italic,
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.black87,
            ),
          ),
          SizedBox(height: 10),
          Text(content, style: TextStyle(fontSize: 16, color: Colors.black54)),
        ],
      ),
    );
  }

  Widget _buildSubsection(String title, List<String> items) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.black87,
            ),
          ),
          SizedBox(height: 10),
          ...items.map(
            (item) => Padding(
              padding: EdgeInsets.only(left: 20, bottom: 5),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '• ',
                    style: TextStyle(fontSize: 16, color: Colors.black54),
                  ),
                  Expanded(
                    child: Text(
                      item,
                      style: TextStyle(fontSize: 16, color: Colors.black54),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
